/* OctaForge client amalgamated build inspired by LuaJIT
 * Warning: requires lots of virtual memory, takes long to compile
 *
 * Author: Daniel "q66" Kolesa <quaker66@gmail.com>
 * License: see COPYING.txt
 */

#include "engine/engine.h"
#include "game/game.h"

#include "engine/blend.cpp"
#include "engine/serverbrowser.cpp"
#include "intensity/client_system.cpp"
#include "game/game.cpp"
#include "game/server.cpp"
#include "game/client.cpp"
#include "game/render.cpp"
#include "game/weapon.cpp"
#include "shared/tools.cpp"
#include "shared/geom.cpp"
#include "shared/glemu.cpp"
#include "engine/command.cpp"
#include "engine/aa.cpp"
#include "engine/rendertext.cpp"
#include "engine/material.cpp"
#include "engine/octaedit.cpp"
#include "engine/grass.cpp"
#include "engine/physics.cpp"
#include "engine/rendergl.cpp"
#include "engine/renderlights.cpp"
#include "engine/worldio.cpp"
#include "engine/texture.cpp"
#include "engine/console.cpp"
#include "engine/world.cpp"
#include "engine/renderva.cpp"
#include "engine/normal.cpp"
#include "engine/rendermodel.cpp"
#include "engine/main.cpp"
#include "engine/bih.cpp"
#include "engine/octa.cpp"
#include "engine/light.cpp"
#include "engine/water.cpp"
#include "engine/shader.cpp"
#include "engine/rendersky.cpp"
#include "engine/renderparticles.cpp"
#include "engine/octarender.cpp"
#include "engine/server.cpp"
#include "engine/client.cpp"
#include "engine/dynlight.cpp"
#include "engine/stain.cpp"
#include "engine/sound.cpp"
#include "engine/pvs.cpp"
#include "shared/stream.cpp"
#include "shared/zip.cpp"
#include "engine/movie.cpp"
#include "octaforge/of_lua.cpp"
#include "octaforge/of_localserver.cpp"
#include "octaforge/of_world.cpp"
#include "octaforge/of_logger.cpp"
#include "octaforge/of_entities.cpp"
